added threading section
minisodan/OvativeGroup pull request #21
Opened 2024-04-23 18:37 UTC by Omarelsegeiny

Should be added as a subsection into the technical low-level overview

2024-04-23 20:51 UTC, KingPhilip14 requested changes
If we can add the docstrings to the rst file, I think that will help since we're trying to explain the code more in depth. Explaining each method would be best to accomplish this.

2024-04-23 20:51 UTC, KingPhilip14 commented on docs/build/html/_sources/threads.rst
> +    a basic constructor, along with setters and getters for properties needed to retun for the output
Misspelled "return" while saying, "...properties needed to **_retun_** for the output..."

2024-04-23 20:51 UTC, KingPhilip14 commented on docs/build/html/_sources/threads.rst
> +    Class that represents a thread instance salesforce BLIP image captioning model. Includes
The writing you've done overall is well done. I would recommend taking the docstrings from each method in these classes and expanding on them here. That is, take the docstrings that explains what each method is and expand on them as you see fit. If the docstrings are written well enough, they can be put here as is.

2024-04-23 20:51 UTC, KingPhilip14 commented on docs/build/html/_sources/threads.rst
> +    Class that represents a thread instance easyOCR model. Includes
Same thing here, where any docstrings in this file should be added here and expanded upon as needed.

2024-04-25 16:38 UTC, KingPhilip14 requested changes
Some small changes, but this is really good!

2024-04-25 16:38 UTC, KingPhilip14 commented on docs/source/threads.rst
> +    along with getters for properties needed to return for the output
Capitalize "along"

2024-04-25 16:38 UTC, KingPhilip14 commented on docs/source/threads.rst
> +        self.captions = bi.caption_image(self.image, self.processor, self.model)
Make sure this line is indented where it says "self.captions"

2024-04-25 16:57 UTC, minisodan approved these changes
be more specific on why we needed threading in the first paragraph

2024-04-25 17:14 UTC, merged