App
minisodan/OvativeGroup pull request #25
Opened 2024-04-25 17:52 UTC by KingPhilip14

Added the documentation for the app module.

2024-04-25 18:03 UTC, Omarelsegeiny commented on docs/source/index.rst
> +   threads
We might wanna capitalize these

2024-04-25 18:05 UTC, Omarelsegeiny approved these changes

2024-04-25 18:11 UTC, minisodan commented on docs/build/html/_sources/app.rst
> +The `App` Module contains two files in it, `image_processor.py` and `input_manager.py`. When the application starts,
in the initial paragraph you say "its these two files" this is nit picky but id change the wording to not make it seem like you are talking to an audience. maybe something like "these two files initiate..."

2024-04-25 18:16 UTC, minisodan requested changes

2024-04-25 18:16 UTC, minisodan commented on docs/build/html/_sources/app.rst
> +This method will start the application and is called in the `runner.py` file. It will first prompt the user for a
This is a common issue in this file try not to start a documentation with "This method"

2024-04-25 18:16 UTC, minisodan commented on docs/build/html/_sources/app.rst
> +it's these two files that initiate the process of processing the given images and accepting user input respectively.
in the initial paragraph you say "its these two files" this is nit picky but id change the wording to not make it seem like you are talking to an audience. maybe something like "these two files initiate..."

2024-04-26 01:16 UTC, minisodan approved these changes

2024-04-26 01:30 UTC, merged